import { CatalogEntity } from 'store/CatalogItemsStore';

export const CatalogData: CatalogEntity[] = [
  {
    'id': 1,
    'title': 'Братья Карамазовы',
    'amount': 63,
    'author': 'Ф. М. Достоевский',
    'price': 1451,
    'popularity': 39,
    'tags': [
      'detectives',
    ],
    'img': 'https://s1.livelib.ru/boocover/1001222161/200/7424/Fjodor_Dostoevskij__Bratya_Karamazovy.jpg',
  },
  {
    'id': 2,
    'title': 'Спасите Котика!',
    'amount': 92,
    'author': 'Блейк Снайдер',
    'price': 815,
    'popularity': 12,
    'tags': [
      'fantasy',
      'comic',
    ],
    'img': 'https://blog-house.pro/arfs/9/f/5/3/9f53-d870-10571bb/e/115359284aada4b947.jpg',
  },
  {
    'id': 3,
    'title': 'Пражское кладбище',
    'amount': 87,
    'author': '',
    'price': 778,
    'popularity': 16,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/54/54315.jpg',
  },
  {
    'id': 4,
    'title': 'Поединок с изменой',
    'amount': 36,
    'author': 'Н. С. Толстая',
    'price': 1513,
    'popularity': 28,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/56/56630.jpg',
  },
  {
    'id': 5,
    'title': 'Похороните меня за плинтусом',
    'amount': 34,
    'author': 'П. С. Санаев',
    'price': 1402,
    'popularity': 12,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/57/57401.jpg',
  },
  {
    'id': 6,
    'title': 'Сандро из Чегема',
    'amount': 99,
    'author': 'Ф. С. Искандер',
    'price': 1045,
    'popularity': 87,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/55/55683.jpg',
  },
  {
    'id': 7,
    'title': 'Рассказы о Родине',
    'amount': 55,
    'author': 'Д. С. Глуховский',
    'price': 907,
    'popularity': 63,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/55/55588.jpg',
  },
  {
    'id': 8,
    'title': 'Ревизор',
    'amount': 69,
    'author': 'Н. В. Гоголь',
    'price': 414,
    'popularity': 46,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/53/53952.jpg',
  },
  {
    'id': 9,
    'title': 'Ржавчина',
    'amount': 14,
    'author': 'А. С. Калугин',
    'price': 880,
    'popularity': 15,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/55/55686.jpg',
  },
  {
    'id': 10,
    'title': 'Сантехник, его кот, жена и другие подробности',
    'amount': 73,
    'author': 'А. С. Пушкин',
    'price': 1021,
    'popularity': 21,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/56/56548.jpg',
  },
  {
    'id': 11,
    'title': 'Пьесы',
    'amount': 77,
    'author': 'А. П. Чехов',
    'price': 1523,
    'popularity': 12,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/54/54293.jpg',
  },
  {
    'id': 12,
    'title': 'Рассказы',
    'amount': 61,
    'author': 'А. П. Чехо',
    'price': 1211,
    'popularity': 69,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/54/54292.jpg',
  },
  {
    'id': 13,
    'title': 'Альтист Данилов',
    'amount': 53,
    'author': 'В. С. Орлов',
    'price': 812,
    'popularity': 99,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/54/54100.jpg',
  },
  {
    'id': 14,
    'title': 'Анатом',
    'amount': 27,
    'author': 'Ф. С. Андахази',
    'price': 1140,
    'popularity': 4,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/55/55457.jpg',
  },
  {
    'id': 15,
    'title': 'Аптекарь',
    'amount': 46,
    'author': 'В. С. Орлов',
    'price': 1021,
    'popularity': 54,
    'tags': [
      'detectives',
    ],
    'img': 'https://www.golddisk.ru/goods_img_small/54/54101.jpg',
  },
];