import { CatalogEntity } from 'store/CatalogItemsStore';

export const CatalogData: CatalogEntity[] = [
  {
    'id': 1,
    'title': 'Год с чудачкой',
    'amount': 63,
    'author': 'А. С. Пушкин',
    'price': 1451,
    'popularity': 39,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 2,
    'title': 'Год с чудачкой',
    'amount': 92,
    'author': 'А. С. Пушкин',
    'price': 815,
    'popularity': 12,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 3,
    'title': 'Год с чудачкой',
    'amount': 87,
    'author': 'А. С. Пушкин',
    'price': 778,
    'popularity': 16,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 4,
    'title': 'Год с чудачкой',
    'amount': 36,
    'author': 'А. С. Пушкин',
    'price': 1513,
    'popularity': 28,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 5,
    'title': 'Год с чудачкой',
    'amount': 34,
    'author': 'А. С. Пушкин',
    'price': 1402,
    'popularity': 12,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 6,
    'title': 'Год с чудачкой',
    'amount': 99,
    'author': 'А. С. Пушкин',
    'price': 1045,
    'popularity': 87,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 7,
    'title': 'Год с чудачкой',
    'amount': 55,
    'author': 'А. С. Пушкин',
    'price': 907,
    'popularity': 63,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 8,
    'title': 'Год с чудачкой',
    'amount': 69,
    'author': 'А. С. Пушкин',
    'price': 414,
    'popularity': 46,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 9,
    'title': 'Год с чудачкой',
    'amount': 14,
    'author': 'А. С. Пушкин',
    'price': 880,
    'popularity': 15,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 10,
    'title': 'Год с чудачкой',
    'amount': 73,
    'author': 'А. С. Пушкин',
    'price': 686,
    'popularity': 54,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 11,
    'title': 'Год с чудачкой',
    'amount': 77,
    'author': 'А. С. Пушкин',
    'price': 1523,
    'popularity': 12,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 12,
    'title': 'Год с чудачкой',
    'amount': 61,
    'author': 'А. С. Пушкин',
    'price': 1211,
    'popularity': 69,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 13,
    'title': 'Год с чудачкой',
    'amount': 53,
    'author': 'А. С. Пушкин',
    'price': 812,
    'popularity': 99,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 14,
    'title': 'Год с чудачкой',
    'amount': 27,
    'author': 'А. С. Пушкин',
    'price': 1140,
    'popularity': 4,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
  {
    'id': 15,
    'title': 'Год с чудачкой',
    'amount': 46,
    'author': 'А. С. Пушкин',
    'price': 1021,
    'popularity': 21,
    'tags': [
      'detectives',
    ],
    'img': 'http://www.vasterad.com/themes/nevia/images/shop/shop-01.jpg',
  },
];